# =============================================================================
# Reusable Workflow: Full ALM Pipeline
# =============================================================================
# Complete ALM pipeline that exports a solution from source environment,
# optionally builds plugins, and deploys to target environment.
#
# Features:
#   - Export from source environment (managed or unmanaged)
#   - Optional .NET solution build for plugins
#   - Optional plugin assembly/package copy to solution
#   - Pack solution for deployment
#   - Deploy to target environment with version checking
#   - Deployment settings auto-detection
#
# Usage:
#   jobs:
#     alm:
#       uses: joshsmithxrm/ppds-alm/github/workflows/full-alm.yml@v1
#       with:
#         solution-name: MySolution
#         solution-folder: solutions/MySolution/src
#         deploy-managed: 'true'
#         build-plugins: 'true'
#         dotnet-solution-path: MySolution.sln
#       secrets:
#         source-environment-url: ${{ vars.SOURCE_ENVIRONMENT_URL }}
#         source-tenant-id: ${{ vars.SOURCE_TENANT_ID }}
#         source-client-id: ${{ vars.SOURCE_CLIENT_ID }}
#         source-client-secret: ${{ secrets.SOURCE_CLIENT_SECRET }}
#         target-environment-url: ${{ vars.TARGET_ENVIRONMENT_URL }}
#         target-tenant-id: ${{ vars.TARGET_TENANT_ID }}
#         target-client-id: ${{ vars.TARGET_CLIENT_ID }}
#         target-client-secret: ${{ secrets.TARGET_CLIENT_SECRET }}
#
# =============================================================================

name: Full ALM Pipeline

on:
  workflow_call:
    inputs:
      solution-name:
        description: 'Solution unique name'
        required: true
        type: string
      solution-folder:
        description: 'Path to unpacked solution folder (e.g., solutions/MySolution/src)'
        required: true
        type: string
      deploy-managed:
        description: 'Deploy as managed solution'
        required: false
        type: boolean
        default: true
      build-plugins:
        description: 'Build .NET solution for plugins/custom code'
        required: false
        type: boolean
        default: false
      dotnet-solution-path:
        description: 'Path to .NET solution file (required if build-plugins is true)'
        required: false
        type: string
        default: ''
      deploy-ppds-plugins:
        description: 'Deploy plugins using PPDS.Tools after solution import (NOT IMPLEMENTED)'
        required: false
        type: boolean
        default: false
      plugin-registration-file:
        description: 'Path to plugin registrations JSON file (NOT IMPLEMENTED)'
        required: false
        type: string
        default: './registrations.json'
      skip-if-same-version:
        description: 'Skip deployment if target has same or newer version'
        required: false
        type: boolean
        default: true

    secrets:
      source-environment-url:
        description: 'Source Dataverse environment URL'
        required: true
      source-tenant-id:
        description: 'Azure AD tenant ID for source environment'
        required: true
      source-client-id:
        description: 'Service principal client ID for source environment'
        required: true
      source-client-secret:
        description: 'Service principal client secret for source environment'
        required: true
      target-environment-url:
        description: 'Target Dataverse environment URL'
        required: true
      target-tenant-id:
        description: 'Azure AD tenant ID for target environment'
        required: true
      target-client-id:
        description: 'Service principal client ID for target environment'
        required: true
      target-client-secret:
        description: 'Service principal client secret for target environment'
        required: true

    outputs:
      exported:
        description: 'Whether export completed successfully'
        value: ${{ jobs.export.outputs.exported }}
      deployed:
        description: 'Whether deployment completed successfully'
        value: ${{ jobs.deploy.outputs.deployed }}
      skipped:
        description: 'Whether deployment was skipped (version match)'
        value: ${{ jobs.deploy.outputs.skipped }}
      version:
        description: 'Solution version that was deployed'
        value: ${{ jobs.deploy.outputs.version }}

jobs:
  export:
    name: Export from Source
    runs-on: ubuntu-latest

    outputs:
      exported: ${{ steps.export.conclusion == 'success' }}
      version: ${{ steps.get-version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup PAC CLI
        uses: ./.github/actions/setup-pac-cli

      - name: Authenticate to source environment
        uses: ./.github/actions/pac-auth
        with:
          environment-url: ${{ secrets.source-environment-url }}
          tenant-id: ${{ secrets.source-tenant-id }}
          client-id: ${{ secrets.source-client-id }}
          client-secret: ${{ secrets.source-client-secret }}

      - name: Export solution
        id: export
        uses: ./.github/actions/export-solution
        with:
          solution-name: ${{ inputs.solution-name }}
          output-folder: ${{ inputs.solution-folder }}
          temp-folder: ./exports

      - name: Get exported version
        id: get-version
        run: |
          SOLUTION_XML="${{ inputs.solution-folder }}/Other/Solution.xml"
          if [ -f "$SOLUTION_XML" ]; then
            VERSION=$(grep -oP '(?<=<Version>)[^<]+' "$SOLUTION_XML" | head -1 || echo "unknown")
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "Exported solution version: $VERSION"
          else
            echo "version=unknown" >> $GITHUB_OUTPUT
            echo "::warning::Solution.xml not found"
          fi

      - name: Upload solution source
        uses: actions/upload-artifact@v6
        with:
          name: solution-${{ inputs.solution-name }}-source
          path: ${{ inputs.solution-folder }}
          retention-days: 7

  build:
    name: Build Plugins
    runs-on: ubuntu-latest
    needs: export
    if: inputs.build-plugins

    outputs:
      build-succeeded: ${{ steps.build.outputs.build-succeeded }}
      classic-assembly: ${{ steps.build.outputs.classic-assembly-path }}
      plugin-package: ${{ steps.build.outputs.plugin-package-path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download solution source
        uses: actions/download-artifact@v7
        with:
          name: solution-${{ inputs.solution-name }}-source
          path: ${{ inputs.solution-folder }}

      - name: Build solution
        id: build
        uses: ./.github/actions/build-solution
        with:
          solution-path: ${{ inputs.dotnet-solution-path }}
          configuration: Release
          run-tests: 'false'

      - name: Copy plugin assemblies
        if: steps.build.outputs.classic-assembly-path != ''
        uses: ./.github/actions/copy-plugin-assemblies
        with:
          source-assembly: ${{ steps.build.outputs.classic-assembly-path }}
          solution-folder: ${{ inputs.solution-folder }}

      - name: Copy plugin packages
        if: steps.build.outputs.plugin-package-path != ''
        uses: ./.github/actions/copy-plugin-packages
        with:
          source-package: ${{ steps.build.outputs.plugin-package-path }}
          solution-folder: ${{ inputs.solution-folder }}

      - name: Upload updated solution
        uses: actions/upload-artifact@v6
        with:
          name: solution-${{ inputs.solution-name }}-built
          path: ${{ inputs.solution-folder }}
          retention-days: 7

  pack:
    name: Pack Solution
    runs-on: ubuntu-latest
    needs: [export, build]
    if: always() && needs.export.outputs.exported == 'true'

    outputs:
      solution-path: ${{ steps.pack.outputs.solution-path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download solution source
        if: inputs.build-plugins == false
        uses: actions/download-artifact@v7
        with:
          name: solution-${{ inputs.solution-name }}-source
          path: ${{ inputs.solution-folder }}

      - name: Download built solution
        if: inputs.build-plugins == true
        uses: actions/download-artifact@v7
        with:
          name: solution-${{ inputs.solution-name }}-built
          path: ${{ inputs.solution-folder }}

      - name: Setup PAC CLI
        uses: ./.github/actions/setup-pac-cli

      - name: Pack solution
        id: pack
        uses: ./.github/actions/pack-solution
        with:
          solution-folder: ${{ inputs.solution-folder }}
          solution-name: ${{ inputs.solution-name }}
          output-folder: ./exports
          package-type: ${{ inputs.deploy-managed && 'Managed' || 'Unmanaged' }}

      - name: Upload solution package
        uses: actions/upload-artifact@v6
        with:
          name: solution-${{ inputs.solution-name }}-package
          path: ${{ steps.pack.outputs.solution-path }}
          retention-days: 7

  deploy:
    name: Deploy to Target
    runs-on: ubuntu-latest
    needs: [export, pack]
    if: always() && needs.export.outputs.exported == 'true'

    outputs:
      deployed: ${{ steps.import.outputs.imported }}
      skipped: ${{ steps.import.outputs.skipped }}
      version: ${{ needs.export.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download solution package
        uses: actions/download-artifact@v7
        with:
          name: solution-${{ inputs.solution-name }}-package
          path: ./exports

      - name: Setup PAC CLI
        uses: ./.github/actions/setup-pac-cli

      - name: Authenticate to target environment
        uses: ./.github/actions/pac-auth
        with:
          environment-url: ${{ secrets.target-environment-url }}
          tenant-id: ${{ secrets.target-tenant-id }}
          client-id: ${{ secrets.target-client-id }}
          client-secret: ${{ secrets.target-client-secret }}

      - name: Detect deployment settings file
        id: detect-settings
        run: |
          PACKAGE_TYPE="${{ inputs.deploy-managed && 'Managed' || 'Unmanaged' }}"
          PACKAGE_TYPE_LOWER=$(echo "$PACKAGE_TYPE" | tr '[:upper:]' '[:lower:]')
          SOLUTION_PATH="./exports/${{ inputs.solution-name }}_${PACKAGE_TYPE_LOWER}.zip"

          # Look for deployment settings file
          # Convention: {SolutionName}.{Environment}.deploymentsettings.json
          # Try to detect environment name from URL
          ENV_URL="${{ secrets.target-environment-url }}"
          ENV_NAME=$(echo "$ENV_URL" | sed -E 's|https://([^.]+)\..*|\1|')

          SETTINGS_FILE=""

          # Try specific environment name
          if [ -f "./config/${{ inputs.solution-name }}.${ENV_NAME}.deploymentsettings.json" ]; then
            SETTINGS_FILE="./config/${{ inputs.solution-name }}.${ENV_NAME}.deploymentsettings.json"
          # Try generic
          elif [ -f "./config/${{ inputs.solution-name }}.deploymentsettings.json" ]; then
            SETTINGS_FILE="./config/${{ inputs.solution-name }}.deploymentsettings.json"
          # Try at solution folder level
          elif [ -f "${{ inputs.solution-folder }}/../config/${{ inputs.solution-name }}.deploymentsettings.json" ]; then
            SETTINGS_FILE="${{ inputs.solution-folder }}/../config/${{ inputs.solution-name }}.deploymentsettings.json"
          fi

          if [ -n "$SETTINGS_FILE" ]; then
            echo "Found deployment settings: $SETTINGS_FILE"
            echo "settings-file=$SETTINGS_FILE" >> $GITHUB_OUTPUT
          else
            echo "No deployment settings file found"
            echo "settings-file=" >> $GITHUB_OUTPUT
          fi

          echo "solution-path=$SOLUTION_PATH" >> $GITHUB_OUTPUT

      - name: Import solution
        id: import
        uses: ./.github/actions/import-solution
        with:
          solution-path: ${{ steps.detect-settings.outputs.solution-path }}
          solution-name: ${{ inputs.solution-name }}
          skip-if-same-version: ${{ inputs.skip-if-same-version && 'true' || 'false' }}
          max-retries: 3
          settings-file: ${{ steps.detect-settings.outputs.settings-file }}
          publish-changes: 'true'

      - name: Deploy plugins with PPDS.Tools
        if: inputs.deploy-ppds-plugins
        run: |
          echo "::error::PPDS plugin deployment not yet implemented in this workflow"
          echo "This feature requires PPDS.Tools installation and configuration"
          exit 1

  summary:
    name: Pipeline Summary
    runs-on: ubuntu-latest
    needs: [export, build, pack, deploy]
    if: always()

    steps:
      - name: Generate summary
        run: |
          echo "## ALM Pipeline Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Stage | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY

          # Export status
          if [ "${{ needs.export.result }}" = "success" ]; then
            echo "| Export | **Success** |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Export | **Failed** |" >> $GITHUB_STEP_SUMMARY
          fi

          # Build status (if applicable)
          if [ "${{ inputs.build-plugins }}" = "true" ]; then
            if [ "${{ needs.build.result }}" = "success" ]; then
              echo "| Build | **Success** |" >> $GITHUB_STEP_SUMMARY
            elif [ "${{ needs.build.result }}" = "skipped" ]; then
              echo "| Build | Skipped |" >> $GITHUB_STEP_SUMMARY
            else
              echo "| Build | **Failed** |" >> $GITHUB_STEP_SUMMARY
            fi
          fi

          # Pack status
          if [ "${{ needs.pack.result }}" = "success" ]; then
            echo "| Pack | **Success** |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Pack | **Failed** |" >> $GITHUB_STEP_SUMMARY
          fi

          # Deploy status
          if [ "${{ needs.deploy.outputs.skipped }}" = "true" ]; then
            echo "| Deploy | **Skipped** (version match) |" >> $GITHUB_STEP_SUMMARY
          elif [ "${{ needs.deploy.result }}" = "success" ]; then
            echo "| Deploy | **Success** |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Deploy | **Failed** |" >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Property | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Solution | ${{ inputs.solution-name }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Version | ${{ needs.export.outputs.version }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Package Type | ${{ inputs.deploy-managed && 'Managed' || 'Unmanaged' }} |" >> $GITHUB_STEP_SUMMARY
