# =============================================================================
# Reusable Workflow: Import Solution
# =============================================================================
# Imports a Power Platform solution into a Dataverse environment.
#
# Features:
#   - Version comparison (skip if target has same/newer version)
#   - Smart retry logic for transient failures
#   - Deployment settings file support
#   - Detailed import summary
#
# Usage:
#   jobs:
#     import:
#       uses: joshsmithxrm/ppds-alm/github/workflows/solution-import.yml@v2
#       with:
#         solution-path: ./exports/MySolution_managed.zip
#         solution-name: MySolution
#       secrets:
#         environment-url: ${{ vars.POWERPLATFORM_ENVIRONMENT_URL }}
#         tenant-id: ${{ vars.POWERPLATFORM_TENANT_ID }}
#         client-id: ${{ vars.POWERPLATFORM_CLIENT_ID }}
#         client-secret: ${{ secrets.POWERPLATFORM_CLIENT_SECRET }}
#
# =============================================================================

name: Import Solution

on:
  workflow_call:
    inputs:
      solution-path:
        description: 'Path to solution zip file to import'
        required: true
        type: string
      solution-name:
        description: 'Solution unique name (required for version check)'
        required: false
        type: string
        default: ''
      skip-if-same-version:
        description: 'Skip import if target has same or newer version'
        required: false
        type: boolean
        default: true
      max-retries:
        description: 'Maximum retry attempts for transient failures'
        required: false
        type: number
        default: 3
      settings-file:
        description: 'Path to deployment settings JSON file'
        required: false
        type: string
        default: ''
      publish-changes:
        description: 'Publish customizations after import'
        required: false
        type: boolean
        default: true

    secrets:
      environment-url:
        description: 'Power Platform environment URL'
        required: true
      tenant-id:
        description: 'Azure AD tenant ID'
        required: true
      client-id:
        description: 'Service principal client ID'
        required: true
      client-secret:
        description: 'Service principal client secret'
        required: true

    outputs:
      deployed:
        description: 'Whether deployment completed successfully'
        value: ${{ jobs.import.outputs.deployed }}
      skipped:
        description: 'Whether deployment was skipped (version match)'
        value: ${{ jobs.import.outputs.skipped }}
      import-version:
        description: 'Version that was imported'
        value: ${{ jobs.import.outputs.import-version }}
      target-version:
        description: 'Version in target environment before import'
        value: ${{ jobs.import.outputs.target-version }}

jobs:
  import:
    name: Import Solution
    runs-on: ubuntu-latest

    outputs:
      deployed: ${{ steps.import.outputs.imported }}
      skipped: ${{ steps.import.outputs.skipped }}
      import-version: ${{ steps.import.outputs.import-version }}
      target-version: ${{ steps.import.outputs.target-version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download solution artifact
        uses: actions/download-artifact@v7
        with:
          pattern: solution-*
          path: ./artifacts
          merge-multiple: true
        continue-on-error: true

      - name: Setup PAC CLI
        uses: ./.github/actions/setup-pac-cli

      - name: Authenticate to environment
        uses: ./.github/actions/pac-auth
        with:
          environment-url: ${{ secrets.environment-url }}
          tenant-id: ${{ secrets.tenant-id }}
          client-id: ${{ secrets.client-id }}
          client-secret: ${{ secrets.client-secret }}

      - name: Import solution
        id: import
        uses: ./.github/actions/import-solution
        with:
          solution-path: ${{ inputs.solution-path }}
          solution-name: ${{ inputs.solution-name }}
          skip-if-same-version: ${{ inputs.skip-if-same-version && 'true' || 'false' }}
          max-retries: ${{ inputs.max-retries }}
          settings-file: ${{ inputs.settings-file }}
          publish-changes: ${{ inputs.publish-changes && 'true' || 'false' }}
