# azure-devops/templates/full-alm.yml
# Template: Complete ALM pipeline (export, build, import, deploy plugins)
parameters:
  - name: sourceEnvironmentUrl
    displayName: 'Source Dataverse environment URL for export'
    type: string

  - name: targetEnvironmentUrl
    displayName: 'Target Dataverse environment URL for import'
    type: string

  - name: solutionName
    displayName: 'Unique name of the solution'
    type: string

  - name: deployManaged
    displayName: 'Deploy as managed solution'
    type: boolean
    default: true

  - name: deployPlugins
    displayName: 'Deploy plugins after solution import'
    type: boolean
    default: true

  - name: pluginRegistrationFile
    displayName: 'Path to plugin registrations JSON file'
    type: string
    default: './registrations.json'

  - name: sourceServiceConnection
    displayName: 'Azure Service Connection for source environment'
    type: string

  - name: targetServiceConnection
    displayName: 'Azure Service Connection for target environment'
    type: string

  - name: workingDirectory
    displayName: 'Working directory'
    type: string
    default: '$(System.DefaultWorkingDirectory)'

stages:
  - stage: Export
    displayName: 'Export from Source'
    jobs:
      - job: ExportSolution
        displayName: 'Export Solution'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: PowerPlatformToolInstaller@2
            displayName: 'Install Power Platform Build Tools'
            inputs:
              DefaultVersion: true

          - task: PowerShell@2
            displayName: 'Create Export Directory'
            inputs:
              targetType: 'inline'
              script: |
                New-Item -ItemType Directory -Force -Path "./export"
              pwsh: true
              workingDirectory: ${{ parameters.workingDirectory }}

          - task: PowerPlatformExportSolution@2
            displayName: 'Export Solution'
            inputs:
              authenticationType: 'PowerPlatformSPN'
              PowerPlatformSPN: ${{ parameters.sourceServiceConnection }}
              Environment: ${{ parameters.sourceEnvironmentUrl }}
              SolutionName: ${{ parameters.solutionName }}
              SolutionOutputFile: './export/${{ parameters.solutionName }}${{ parameters.deployManaged }}_managed.zip'
              Managed: ${{ parameters.deployManaged }}

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Solution Artifact'
            inputs:
              targetPath: '${{ parameters.workingDirectory }}/export'
              artifact: 'solution'
              publishLocation: 'pipeline'

  - stage: Import
    displayName: 'Import to Target'
    dependsOn: Export
    jobs:
      - job: ImportSolution
        displayName: 'Import Solution'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: DownloadPipelineArtifact@2
            displayName: 'Download Solution'
            inputs:
              buildType: 'current'
              artifactName: 'solution'
              targetPath: '${{ parameters.workingDirectory }}/import'

          - task: PowerPlatformToolInstaller@2
            displayName: 'Install Power Platform Build Tools'
            inputs:
              DefaultVersion: true

          - task: PowerShell@2
            displayName: 'Find Solution File'
            inputs:
              targetType: 'inline'
              script: |
                $solutionFile = Get-ChildItem -Path "./import" -Filter "*.zip" | Select-Object -First 1
                Write-Host "Found solution: $($solutionFile.FullName)"
                Write-Host "##vso[task.setvariable variable=SolutionFile]$($solutionFile.FullName)"
              pwsh: true
              workingDirectory: ${{ parameters.workingDirectory }}

          - task: PowerPlatformImportSolution@2
            displayName: 'Import Solution'
            inputs:
              authenticationType: 'PowerPlatformSPN'
              PowerPlatformSPN: ${{ parameters.targetServiceConnection }}
              Environment: ${{ parameters.targetEnvironmentUrl }}
              SolutionInputFile: '$(SolutionFile)'
              PublishWorkflows: true
              OverwriteUnmanagedCustomizations: false

          - task: PowerPlatformPublishCustomizations@2
            displayName: 'Publish Customizations'
            inputs:
              authenticationType: 'PowerPlatformSPN'
              PowerPlatformSPN: ${{ parameters.targetServiceConnection }}
              Environment: ${{ parameters.targetEnvironmentUrl }}

  - ${{ if eq(parameters.deployPlugins, true) }}:
    - stage: DeployPlugins
      displayName: 'Deploy Plugins'
      dependsOn: Import
      jobs:
        - job: Deploy
          displayName: 'Deploy Plugins'
          pool:
            vmImage: 'ubuntu-latest'
          steps:
            - checkout: self

            - task: PowerShell@2
              displayName: 'Install PPDS.Tools'
              inputs:
                targetType: 'inline'
                script: |
                  Set-PSRepository PSGallery -InstallationPolicy Trusted
                  Install-Module PPDS.Tools -Force -Scope CurrentUser
                  Import-Module PPDS.Tools
                pwsh: true
                workingDirectory: ${{ parameters.workingDirectory }}

            - task: AzureCLI@2
              displayName: 'Get Service Principal Credentials'
              inputs:
                azureSubscription: ${{ parameters.targetServiceConnection }}
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  Write-Host "##vso[task.setvariable variable=AZURE_CLIENT_ID;issecret=false]$env:servicePrincipalId"
                  Write-Host "##vso[task.setvariable variable=AZURE_CLIENT_SECRET;issecret=true]$env:servicePrincipalKey"
                  Write-Host "##vso[task.setvariable variable=AZURE_TENANT_ID;issecret=false]$env:tenantId"
                addSpnToEnvironment: true

            - task: PowerShell@2
              displayName: 'Connect and Deploy Plugins'
              inputs:
                targetType: 'inline'
                script: |
                  Import-Module PPDS.Tools

                  $secureSecret = ConvertTo-SecureString "$(AZURE_CLIENT_SECRET)" -AsPlainText -Force
                  Connect-DataverseEnvironment `
                    -EnvironmentUrl "${{ parameters.targetEnvironmentUrl }}" `
                    -ClientId "$(AZURE_CLIENT_ID)" `
                    -ClientSecret $secureSecret `
                    -TenantId "$(AZURE_TENANT_ID)"

                  Write-Host "Deploying plugins..."
                  Deploy-DataversePlugins `
                    -RegistrationFile "${{ parameters.pluginRegistrationFile }}" `
                    -DetectDrift

                  Write-Host "Plugin deployment complete."
                pwsh: true
                workingDirectory: ${{ parameters.workingDirectory }}
