# azure-devops/templates/plugin-deploy.yml
# Template: Deploy plugins to Dataverse
parameters:
  - name: environmentUrl
    displayName: 'Dataverse Environment URL'
    type: string

  - name: registrationFile
    displayName: 'Path to plugin registrations JSON file'
    type: string
    default: './registrations.json'

  - name: detectDrift
    displayName: 'Run drift detection before deployment'
    type: boolean
    default: true

  - name: serviceConnection
    displayName: 'Azure Service Connection name'
    type: string

  - name: workingDirectory
    displayName: 'Working directory'
    type: string
    default: '$(System.DefaultWorkingDirectory)'

stages:
  - stage: DeployPlugins
    displayName: 'Deploy Plugins'
    jobs:
      - job: Deploy
        displayName: 'Deploy Plugins to Dataverse'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: PowerShell@2
            displayName: 'Install PPDS.Tools'
            inputs:
              targetType: 'inline'
              script: |
                Set-PSRepository PSGallery -InstallationPolicy Trusted
                Install-Module PPDS.Tools -Force -Scope CurrentUser
                Import-Module PPDS.Tools
                Get-Command -Module PPDS.Tools
              pwsh: true
              workingDirectory: ${{ parameters.workingDirectory }}

          - task: AzureCLI@2
            displayName: 'Get Service Principal Credentials'
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Service connection credentials are available via environment variables
                Write-Host "##vso[task.setvariable variable=AZURE_CLIENT_ID;issecret=false]$env:servicePrincipalId"
                Write-Host "##vso[task.setvariable variable=AZURE_CLIENT_SECRET;issecret=true]$env:servicePrincipalKey"
                Write-Host "##vso[task.setvariable variable=AZURE_TENANT_ID;issecret=false]$env:tenantId"
              addSpnToEnvironment: true

          - task: PowerShell@2
            displayName: 'Connect to Dataverse'
            inputs:
              targetType: 'inline'
              script: |
                Import-Module PPDS.Tools
                $secureSecret = ConvertTo-SecureString "$(AZURE_CLIENT_SECRET)" -AsPlainText -Force
                Connect-DataverseEnvironment `
                  -EnvironmentUrl "${{ parameters.environmentUrl }}" `
                  -ClientId "$(AZURE_CLIENT_ID)" `
                  -ClientSecret $secureSecret `
                  -TenantId "$(AZURE_TENANT_ID)"
              pwsh: true
              workingDirectory: ${{ parameters.workingDirectory }}

          - ${{ if eq(parameters.detectDrift, true) }}:
            - task: PowerShell@2
              displayName: 'Detect Plugin Drift'
              inputs:
                targetType: 'inline'
                script: |
                  Import-Module PPDS.Tools
                  Write-Host "Detecting plugin drift..."
                  $drift = Get-DataversePluginDrift -RegistrationFile "${{ parameters.registrationFile }}"
                  if ($drift) {
                    Write-Host "##vso[task.logissue type=warning]Plugin drift detected. Review changes below:"
                    $drift | ConvertTo-Json -Depth 10 | Write-Host
                  } else {
                    Write-Host "No drift detected."
                  }
                pwsh: true
                workingDirectory: ${{ parameters.workingDirectory }}

          - task: PowerShell@2
            displayName: 'Deploy Plugins'
            inputs:
              targetType: 'inline'
              script: |
                Import-Module PPDS.Tools
                Write-Host "Deploying plugins from ${{ parameters.registrationFile }}..."
                $params = @{
                  RegistrationFile = "${{ parameters.registrationFile }}"
                }
                if (${{ parameters.detectDrift }}) {
                  $params.DetectDrift = $true
                }
                Deploy-DataversePlugins @params
                Write-Host "Plugin deployment complete."
              pwsh: true
              workingDirectory: ${{ parameters.workingDirectory }}
