# azure-devops/templates/plugin-extract.yml
# Template: Extract plugin registrations from compiled assembly
parameters:
  - name: assemblyPath
    displayName: 'Path to the compiled plugin assembly (.dll)'
    type: string

  - name: outputPath
    displayName: 'Path for the output registrations JSON file'
    type: string
    default: './registrations.json'

  - name: workingDirectory
    displayName: 'Working directory'
    type: string
    default: '$(System.DefaultWorkingDirectory)'

  - name: publishArtifact
    displayName: 'Publish registrations as artifact'
    type: boolean
    default: true

  - name: artifactName
    displayName: 'Name for the published artifact'
    type: string
    default: 'plugin-registrations'

stages:
  - stage: ExtractRegistrations
    displayName: 'Extract Plugin Registrations'
    jobs:
      - job: Extract
        displayName: 'Extract Registrations'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: PowerShell@2
            displayName: 'Install PPDS.Tools'
            inputs:
              targetType: 'inline'
              script: |
                Set-PSRepository PSGallery -InstallationPolicy Trusted
                Install-Module PPDS.Tools -Force -Scope CurrentUser
                Import-Module PPDS.Tools
              pwsh: true
              workingDirectory: ${{ parameters.workingDirectory }}

          - task: PowerShell@2
            displayName: 'Extract Plugin Registrations'
            inputs:
              targetType: 'inline'
              script: |
                Import-Module PPDS.Tools
                Write-Host "Extracting plugin registrations from ${{ parameters.assemblyPath }}..."

                Get-DataversePluginRegistrations `
                  -AssemblyPath "${{ parameters.assemblyPath }}" `
                  -OutputPath "${{ parameters.outputPath }}"

                Write-Host "Registrations extracted to ${{ parameters.outputPath }}"

                # Output for downstream tasks
                Write-Host "##vso[task.setvariable variable=RegistrationFile;isOutput=true]${{ parameters.outputPath }}"
              pwsh: true
              workingDirectory: ${{ parameters.workingDirectory }}
              name: extractStep

          - ${{ if eq(parameters.publishArtifact, true) }}:
            - task: PublishPipelineArtifact@1
              displayName: 'Publish Registrations Artifact'
              inputs:
                targetPath: '${{ parameters.workingDirectory }}/${{ parameters.outputPath }}'
                artifact: '${{ parameters.artifactName }}'
                publishLocation: 'pipeline'
