# azure-devops/templates/solution-import.yml
# Template: Import solution to Dataverse environment
parameters:
  - name: environmentUrl
    displayName: 'Dataverse Environment URL'
    type: string

  - name: solutionFile
    displayName: 'Path to the solution zip file to import'
    type: string

  - name: publishChanges
    displayName: 'Publish customizations after import'
    type: boolean
    default: true

  - name: activatePlugins
    displayName: 'Activate plugin steps after import'
    type: boolean
    default: true

  - name: overwriteUnmanaged
    displayName: 'Overwrite unmanaged customizations'
    type: boolean
    default: false

  - name: serviceConnection
    displayName: 'Azure Service Connection name'
    type: string

  - name: workingDirectory
    displayName: 'Working directory'
    type: string
    default: '$(System.DefaultWorkingDirectory)'

stages:
  - stage: ImportSolution
    displayName: 'Import Solution'
    jobs:
      - job: Import
        displayName: 'Import Solution to Dataverse'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - task: DownloadPipelineArtifact@2
            displayName: 'Download Solution Artifact'
            inputs:
              buildType: 'current'
              artifactName: 'solution-*'
              targetPath: '${{ parameters.workingDirectory }}/artifacts'
            continueOnError: true

          - task: PowerPlatformToolInstaller@2
            displayName: 'Install Power Platform Build Tools'
            inputs:
              DefaultVersion: true

          - task: PowerPlatformImportSolution@2
            displayName: 'Import Solution'
            inputs:
              authenticationType: 'PowerPlatformSPN'
              PowerPlatformSPN: ${{ parameters.serviceConnection }}
              Environment: ${{ parameters.environmentUrl }}
              SolutionInputFile: ${{ parameters.solutionFile }}
              PublishWorkflows: ${{ parameters.activatePlugins }}
              OverwriteUnmanagedCustomizations: ${{ parameters.overwriteUnmanaged }}

          - ${{ if eq(parameters.publishChanges, true) }}:
            - task: PowerPlatformPublishCustomizations@2
              displayName: 'Publish Customizations'
              inputs:
                authenticationType: 'PowerPlatformSPN'
                PowerPlatformSPN: ${{ parameters.serviceConnection }}
                Environment: ${{ parameters.environmentUrl }}
