# azure-devops/examples/starter-pipeline.yml
# Example: Basic pipeline using PPDS ALM templates
#
# To use this example:
# 1. Copy this file to your repository as azure-pipelines.yml
# 2. Add ppds-alm as a repository resource
# 3. Configure your service connections
# 4. Update the parameters to match your environment

trigger:
  - main

resources:
  repositories:
    - repository: ppds-alm
      type: github
      name: joshsmithxrm/ppds-alm
      ref: refs/tags/v1.0.0
      endpoint: 'GitHub Connection'  # Your GitHub service connection name

variables:
  - name: solutionName
    value: 'MySolution'
  - name: devEnvironmentUrl
    value: 'https://myorg-dev.crm.dynamics.com'
  - name: prodEnvironmentUrl
    value: 'https://myorg.crm.dynamics.com'

stages:
  # Export from Dev environment
  - template: azure-devops/templates/solution-export.yml@ppds-alm
    parameters:
      environmentUrl: $(devEnvironmentUrl)
      solutionName: $(solutionName)
      managed: false
      serviceConnection: 'Dataverse Dev'

  # Deploy plugins to Dev (for testing)
  - template: azure-devops/templates/plugin-deploy.yml@ppds-alm
    parameters:
      environmentUrl: $(devEnvironmentUrl)
      registrationFile: './src/Plugins/registrations.json'
      detectDrift: true
      serviceConnection: 'Dataverse Dev'
